version: '3.5'

services:
  codeserver-nodejs:
    image: solardesigner/codeserver-nodejs:latest
    container_name: codeserver-nodejs
    command: --allow-http --no-auth --disable-telemetry
    expose:
      - 8443
    ports:
      - 8443:8443  
    restart: always
    volumes:
      - vscode_data:/home/coder/project

volumes:
  vscode_data:
    driver: local
    name: vscode_data